# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ad37bce557bf747ea54f39602c81cc6d75089f3e6245cc4bc6c0c4989786b017f145f71c7accdc839ef4740ca22f2c6df21e004c4e7f8ff130b80d21c7bdaed

test:
  secret_key_base: 67ca17c763594d254ca7998ac7e96981af5326beb0c498d4bd518ad69bde2d100bdd51e1618cce986fcf94a5d0506b7cf220dc904d33b78b86ab67d6df238884

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
